### ISSUE TITLE
Error in compiling generated monitor

### ISSUE THREAD

**Issue by HenriqueMisson** [anmaped/rmtld3synth#4] opened 2018-11-23 12:15 UTC
Hello Andre,

I generated a monitor with the command ``` ./rmtld3synth --synth-cpp11 --input-latexeq "(a \rightarrow ((a \lor b) \until_{<10} c)) \land \int^{10} c < 4" --out-src="mon1" ``` as demonstrated in the readme.

I modified the Makefile to take the correct files path as:
```
arm-monitor:
	 arm-none-eabi-g++ -std=c++0x -mthumb -march=armv7-m -g -fverbose-asm -O -I/home/labvant/ardupilot/modules/PX4NuttX/nuttx/include -Wframe-larger-than=1200 -DCONFIG_WCHAR_BUILTIN -I/home/labvant/rmtld3synth/rtmlib/arch/arm/include -I/home/labvant/rmtld3synth/rtmlib -DARM_CM4_FP -D__NUTTX__ --verbose -c mon1.cpp 
 ```
I'm using the toolchain arm-none-eabi version 4.9.3.
And when I compile with ``` make arm-mon ``` I have these errors:

``` 
GNU C++ (GNU Tools for ARM Embedded Processors) version 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 227977] (arm-none-eabi)
	compiled by GNU C version 4.7.4, GMP version 4.3.2, MPFR version 2.4.2, MPC version 0.8.1
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: b2a48e419865560d4c520822e41296e7
In file included from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/bits/char_traits.h:380:0,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/string:40,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/stdexcept:39,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/array:38,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/tuple:39,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/functional:55,
                 from Rmtld3_reader.h:5,
                 from Mon0.h:5,
                 from mon1.cpp:1:
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cstdint:78:11: error: 'uint_least32_t' is already declared in this scope
   using ::uint_least32_t;
           ^
In file included from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/bits/localefwd.h:42:0,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/string:43,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/stdexcept:39,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/array:38,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/tuple:39,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/functional:55,
                 from Rmtld3_reader.h:5,
                 from Mon0.h:5,
                 from mon1.cpp:1:
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:64:11: error: '::isalnum' has not been declared
   using ::isalnum;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:65:11: error: '::isalpha' has not been declared
   using ::isalpha;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:66:11: error: '::iscntrl' has not been declared
   using ::iscntrl;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:67:11: error: '::isdigit' has not been declared
   using ::isdigit;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:68:11: error: '::isgraph' has not been declared
   using ::isgraph;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:69:11: error: '::islower' has not been declared
   using ::islower;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:70:11: error: '::isprint' has not been declared
   using ::isprint;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:71:11: error: '::ispunct' has not been declared
   using ::ispunct;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:72:11: error: '::isspace' has not been declared
   using ::isspace;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:73:11: error: '::isupper' has not been declared
   using ::isupper;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:74:11: error: '::isxdigit' has not been declared
   using ::isxdigit;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:75:11: error: '::tolower' has not been declared
   using ::tolower;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:76:11: error: '::toupper' has not been declared
   using ::toupper;
           ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cctype:87:11: error: '::isblank' has not been declared
   using ::isblank;
           ^
In file included from /home/labvant/rmtld3synth/rtmlib/CircularBuffer.h:27:0,
                 from /home/labvant/rmtld3synth/rtmlib/RTML_reader.h:6,
                 from Rmtld3_reader.h:9,
                 from Mon0.h:5,
                 from mon1.cpp:1:
/home/labvant/ardupilot/modules/PX4NuttX/nuttx/include/stdio.h:85:28: error: conflicting declaration 'typedef struct file_struct FILE'
 typedef struct file_struct FILE;
                            ^
In file included from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/cwchar:44:0,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/bits/postypes.h:40,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/bits/char_traits.h:40,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/string:40,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/stdexcept:39,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/array:38,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/tuple:39,
                 from /opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/functional:55,
                 from Rmtld3_reader.h:5,
                 from Mon0.h:5,
                 from mon1.cpp:1:
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/wchar.h:53:16: note: previous declaration as 'typedef __FILE FILE'
 typedef __FILE FILE;
                ^
In file included from /home/labvant/rmtld3synth/rtmlib/atomic_compat.h:23:0,
                 from /home/labvant/rmtld3synth/rtmlib/time_compat.h:5,
                 from /home/labvant/rmtld3synth/rtmlib/Event.h:6,
                 from /home/labvant/rmtld3synth/rtmlib/CircularBuffer.h:30,
                 from /home/labvant/rmtld3synth/rtmlib/RTML_reader.h:6,
                 from Rmtld3_reader.h:9,
                 from Mon0.h:5,
                 from mon1.cpp:1:
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/atomic:541:12: error: redefinition of 'struct std::atomic<unsigned char>'
     struct atomic<unsigned char> : public atomic_uchar
            ^
/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/atomic:484:12: error: previous definition of 'struct std::atomic<unsigned char>'
     struct atomic<bool> : public atomic_bool
            ^
Makefile:13: recipe for target 'arm-monitor' failed
make: *** [arm-monitor] Error 1
 ```

Could you help me in this sense, please? I tried many things to fix the errors, but I couldn't resolve.

**Comment by anmaped** [comment] 2018-11-23 13:53
If you are using gcc 4.9 you should remove the forder `rtmlib/arch/arm/include` to avoid duplication or modify the makefile acordingly removing `-I/home/labvant/rmtld3synth/rtmlib/arch/arm/include`.

**Comment by HenriqueMisson** [comment] 2018-11-23 14:37
I removed the link in Makefile, and now the file ``` atomic_compat.h``` can't find the ```ARMCM4_FP.h``` as you can see:

```
GNU C++ (GNU Tools for ARM Embedded Processors) version 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 227977] (arm-none-eabi)
	compiled by GNU C version 4.7.4, GMP version 4.3.2, MPFR version 2.4.2, MPC version 0.8.1
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: b2a48e419865560d4c520822e41296e7
In file included from ../../time_compat.h:5:0,
                 from ../../Event.h:6,
                 from ../../CircularBuffer.h:30,
                 from ../../RTML_reader.h:6,
                 from Rmtld3_reader.h:9,
                 from Mon0.h:5,
                 from mon7.cpp:1:
../../atomic_compat.h:21:24: fatal error: ARMCM4_FP.h: No such file or directory
  #include <ARMCM4_FP.h>
                        ^
compilation terminated.
Makefile:13: recipe for target 'arm-monitor' failed
make: *** [arm-monitor] Error 1
```

**Comment by anmaped** [comment] 2018-11-23 15:03
Yes, you shouldn't remove CMSIS. The problem is with your toolchain.

**Comment by anmaped** [comment] 2018-11-23 15:06
You are using `/home/labvant/ardupilot/modules/PX4NuttX/nuttx/include/stdio.h` and `/opt/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/wchar.h` at the same time and both define the symbol `FILE`.

**Comment by anmaped** [comment] 2018-11-24 00:33
Could you test the rmtld3synth version 8ce6be982aebf35f2168b7f373e2650710cf0d12 ? The makefile is now fixed.

**Comment by HenriqueMisson** [comment] 2018-11-26 11:38
I update my repository and never was changed. 

To see these changes I need to recompiled and reinstall the toolchain?

**Comment by anmaped** [comment] 2018-11-26 14:32
Just reinstall rmtld3synth using `opam`.

**Comment by HenriqueMisson** [comment] 2018-11-26 15:21
I used to remove rmtld3synth and reinstall with opam pin add. But now, I'm in the same issue as #1 : ``` # ocamlfind: package 'z3' not found ```

As you suggested , I typed ```ocamlfind query Z3/z3``` and it was found just Z3 ( ``` /home/labvant/.opam/4.03.0/lib/Z3```). In this sense, I have already searched that  ocamlfind is a case sensitive, but I didn't find where to change the name.

In the topic that I saw, the person changed the " _tags file contained true: package(Z3), I just changed it to true: package(z3) and it compiles."

Do you know where I should to change?

**Comment by anmaped** [comment] 2018-11-26 15:46
Just re-install.

**Comment by HenriqueMisson** [comment] 2018-11-26 17:06
I tried both ```opam pin add rmtld3synth https://github.com/anmaped/rmtld3synth.git``` and ```opam install rmtld3synth``` and now I have other error: ```Error: This expression has type Dolmen.Term.t but an expression was expected of type string * Dolmen.Statement.term option```

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of rmtld3synth failed at "make all".
Processing  1/1: [rmtld3synth: ocamlfind remove]
#=== ERROR while installing rmtld3synth.0.3-dev ===============================#
# opam-version 1.2.2
# os           linux
# command      make all
# path         /home/labvant/.opam/4.03.0/build/rmtld3synth.0.3-dev
# compiler     4.03.0
# exit-code    2
# env-file     /home/labvant/.opam/4.03.0/build/rmtld3synth.0.3-dev/rmtld3synth-7508-a71bb4.env
# stdout-file  /home/labvant/.opam/4.03.0/build/rmtld3synth.0.3-dev/rmtld3synth-7508-a71bb4.out
# stderr-file  /home/labvant/.opam/4.03.0/build/rmtld3synth.0.3-dev/rmtld3synth-7508-a71bb4.err
### stdout ###
# [...]
# findlib: [WARNING] Interface myocamlbuild.cmi occurs in several directories: ., /home/labvant/.opam/4.03.0/lib/dolmen
# ocamlfind ocamlc -c -warn-error A -package unix,type_conv,sexplib,batteries,Z3,dolmen -package dolmen -I src -I src/language -o src/language/smtlib2.cmo src/language/smtlib2.ml
# + ocamlfind ocamlc -c -warn-error A -package unix,type_conv,sexplib,batteries,Z3,dolmen -package dolmen -I src -I src/language -o src/language/smtlib2.cmo src/language/smtlib2.ml
# findlib: [WARNING] Interface myocamlbuild.cmi occurs in several directories: ., /home/labvant/.opam/4.03.0/lib/dolmen
# File "src/language/smtlib2.ml", line 33, characters 30-205:
# Error: This expression has type Dolmen.Term.t
#        but an expression was expected of type
#          string * Dolmen.Statement.term option
# Command exited with code 2.
# Makefile:12: recipe for target 'all' failed
### stderr ###
# make: *** [all] Error 10



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install rmtld3synth 0.3-dev
No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

**Comment by anmaped** [comment] 2018-11-26 17:14
Just do `opam pin add dolmen https://github.com/Gbury/dolmen.git`. Check https://github.com/anmaped/rmtld3synth/blob/master/.travis-opam.sh for reference since you are using a dev version.

**Comment by HenriqueMisson** [comment] 2018-11-27 00:40
I rebuild all from zero and now I tried ```opam pin add dolmen https://github.com/Gbury/dolmen.git```, but I still have problems. From now is to install ```dolmen dev``` as you commented.
```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of dolmen failed at "dune subst".

#=== ERROR while installing dolmen.dev ========================================#
# opam-version 1.2.2
# os           linux
# command      dune subst
# path         /home/labvant/.opam/4.03.0/build/dolmen.dev
# compiler     4.03.0
# exit-code    1
# env-file     /home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-3944-d8a4ae.env
# stdout-file  /home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-3944-d8a4ae.out
# stderr-file  /home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-3944-d8a4ae.err
### stderr ###
# [...]
# | Called from file "src/fiber/fiber.ml", line 56, characters 6-20
# | 
# | Original exception was: Stdune__Exn.Code_error(_)
# | Called from file "camlinternalLazy.ml", line 27, characters 17-27
# | Re-raised at file "camlinternalLazy.ml", line 34, characters 10-11
# | Called from file "src/errors.ml", line 77, characters 17-47
# | Called from file "format.ml", line 1247, characters 20-38
# | Called from file "src/stdune/option.ml", line 23, characters 14-17
# | Called from file "src/fiber/fiber.ml", line 243, characters 6-18
# \-----------------------------------------------------------------------



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install dolmen dev
No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```
Why opam install directly the branch dev from dolmen. It don't have just a dolmen?

**Comment by anmaped** [comment] 2018-11-27 01:19
@HenriqueMisson  Could you try to install dune by typing `opam install dune` ?

**Comment by HenriqueMisson** [comment] 2018-11-27 11:54
I installed dune, ``` Package dune is already installed (current version is 1.2.1).```, but I can't install dolmen.
```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of dolmen failed at "dune subst".

#=== ERROR while installing dolmen.dev ========================================#
# opam-version 1.2.2
# os           linux
# command      dune subst
# path         /home/labvant/.opam/4.03.0/build/dolmen.dev
# compiler     4.03.0
# exit-code    1
# env-file     /home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-25010-d8a4ae.env
# stdout-file  /home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-25010-d8a4ae.out
# stderr-file  /home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-25010-d8a4ae.err
### stderr ###
# [...]
# | Called from file "src/fiber/fiber.ml", line 56, characters 6-20
# | 
# | Original exception was: Stdune__Exn.Code_error(_)
# | Called from file "camlinternalLazy.ml", line 27, characters 17-27
# | Re-raised at file "camlinternalLazy.ml", line 34, characters 10-11
# | Called from file "src/errors.ml", line 77, characters 17-47
# | Called from file "format.ml", line 1247, characters 20-38
# | Called from file "src/stdune/option.ml", line 23, characters 14-17
# | Called from file "src/fiber/fiber.ml", line 243, characters 6-18
# \-----------------------------------------------------------------------

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install dolmen dev
No changes have been performed
```

**Comment by HenriqueMisson** [comment] 2018-11-27 13:36
```
labvant@labvant:~$ opam pin add dolmen https://github.com/Gbury/dolmen.git
[NOTE] Package dolmen is already git-pinned to
       https://github.com/Gbury/dolmen.git.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[dolmen] https://github.com/Gbury/dolmen.git updated
[dolmen] Installing new package description from
https://github.com/Gbury/dolmen.git

dolmen needs to be installed.
The following actions will be performed:
  ∗  install dolmen dev*
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[dolmen] https://github.com/Gbury/dolmen.git already up-to-date

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of dolmen failed at "dune subst".

#=== ERROR while installing dolmen.dev ========================================#
# opam-version 1.2.2
# os           linux
# command      dune subst
# path         /home/labvant/.opam/4.03.0/build/dolmen.dev
# compiler     4.03.0
# exit-code    1
# env-file     /home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-31702-d8a4ae.env
# stdout-file  /home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-31702-d8a4ae.out
# stderr-file  /home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-31702-d8a4ae.err
### stderr ###
# [...]
# | Called from file "src/fiber/fiber.ml", line 56, characters 6-20
# | 
# | Original exception was: Stdune__Exn.Code_error(_)
# | Called from file "camlinternalLazy.ml", line 27, characters 17-27
# | Re-raised at file "camlinternalLazy.ml", line 34, characters 10-11
# | Called from file "src/errors.ml", line 77, characters 17-47
# | Called from file "format.ml", line 1247, characters 20-38
# | Called from file "src/stdune/option.ml", line 23, characters 14-17
# | Called from file "src/fiber/fiber.ml", line 243, characters 6-18
# \-----------------------------------------------------------------------



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install dolmen dev
No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

**Comment by anmaped** [comment] 2018-11-27 13:39
`/home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-31702-d8a4ae.out` and `/home/labvant/.opam/4.03.0/build/dolmen.dev/dolmen-31702-d8a4ae.err`

**Comment by HenriqueMisson** [comment] 2018-11-27 14:31
I'm sorry. The file ".out" is empty and the file ".err" has:

```
/-----------------------------------------------------------------------
| Internal error: Fiber.Execution_context.forward_error: error handler raised.
| Stdune__Exn.Code_error(_)
| Called from file "camlinternalLazy.ml", line 27, characters 17-27
| Re-raised at file "camlinternalLazy.ml", line 34, characters 10-11
| Called from file "src/errors.ml", line 77, characters 17-47
| Called from file "format.ml", line 1247, characters 20-38
| Called from file "src/stdune/option.ml", line 23, characters 14-17
| Called from file "src/fiber/fiber.ml", line 243, characters 6-18
| Called from file "src/fiber/fiber.ml", line 56, characters 6-20
| 
| Original exception was: Stdune__Exn.Code_error(_)
| Called from file "camlinternalLazy.ml", line 27, characters 17-27
| Re-raised at file "camlinternalLazy.ml", line 34, characters 10-11
| Called from file "src/errors.ml", line 77, characters 17-47
| Called from file "format.ml", line 1247, characters 20-38
| Called from file "src/stdune/option.ml", line 23, characters 14-17
| Called from file "src/fiber/fiber.ml", line 243, characters 6-18
\-----------------------------------------------------------------------
```

**Comment by HenriqueMisson** [comment] 2018-11-27 15:22
I updated my opam, and I tried to install the new version of dune (1.5.1) with the command ```opam install dune```, as pin the new repository, but I always came to the same version "dune.1.2.1". 

Do you think a good way download the source from the site " https://opam.ocaml.org/packages/dune/" ?

**Comment by anmaped** [comment] 2018-11-27 16:30
Try to checkout the repo in https://github.com/ocaml/dune and do 
```
$ make release
$ make install
```

I'm using that version right now.

**Comment by HenriqueMisson** [comment] 2018-11-27 17:22
I don't know what is happen.

I uninstall dune  (```opam remove dune```), after I cloned the repo "dune" that you gave me. I compiled and installed dune as you said (```make release``` and ```sudo make install```). So I got 
```
./_build/default/bin/main_dune.exe install   dune
        opam (internal)
[WARNING] Running as root is not recommended
Done: 0/0 (jobs: 1)Installing /usr/local/lib/ocaml/4.02.3/dune/META
Installing /usr/local/lib/ocaml/4.02.3/dune/_caml/dune._caml.dune
...
Installing /home/labvant/.opam/4.03.0/man/man5/dune-config.5
```
and installing all that is described in "dune.install".

After that I tried some things:
- ```opam pin add dolmen https://github.com/Gbury/dolmen.git``` : but it needs to install "dune 1.2.1* " and we get the same error.

- Clone the dolmen repo from git and install manually (```make -C src``` and ```make -C src install```) and to compile I had a message that it don't have "makefile". So I tried only ```make``` and I got the message :
```
dune build --profile release
make: dune: Command not found
Makefile:10: recipe for target 'dune' failed
make: *** [dune] Error 127
```
- Pin "dune" to opam, but it always install "dune 1.2.1" 

So I couldn't install correctly "rmtld3synth" that needs "dolmen" that need "dune".

Do you have any idea?

PS: I'm sorry for that work, but considering that your toolchain is the only I know that can be implemented in my context, I really need it.

**Comment by anmaped** [comment] 2018-11-28 23:59
@HenriqueMisson You can check at https://opam.ocaml.org/packages/dune/ that the last version of dune is 1.5.1.

**Comment by anmaped** [comment] 2018-11-29 00:56
I think I found a clue for you, so unpin dune first (`opam unpin dune`) and then install dune using ```opam pin add dune https://github.com/ocaml/dune/releases/download/1.5.0/dune-1.5.0.tbz```.

**Comment by HenriqueMisson** [comment] 2018-11-29 17:16
I think I could install. In ```opam list``` I have: ```rmtld3synth                 0.3-dev (pinned) ```
And when I type ```which rmtld3synth``` I have as output ```/home/labvant/.opam/4.03.0/bin/rmtld3synth```

But I don't have the folder "rmtld3synth". Should I clone it from github and after install with ```make``` and ```sudo make install``` commands?

**Comment by anmaped** [comment] 2018-11-29 17:29
You have the binary installed in `/home/labvant/.opam/4.03.0/bin/rmtld3synth`. Why you need the folder and why you need to do make?

BTW, you can check the version you are using with `rmtld3synth --version`.

**Comment by HenriqueMisson** [comment] 2018-11-29 17:54
> You have the binary installed in `/home/labvant/.opam/4.03.0/bin/rmtld3synth`. Why you need the folder and why you need to do make?

I'm sorry for the question, but I've never used opam before. The "bin" folder from opam is in my PATH, but I tried to synthesize the monitor as demonstrated by you in the readme,and I have an error like ```Fatal error: exception (Sys_error "config/default: No such file or directory")```
> 
> BTW, you can check the version you are using with `rmtld3synth --version`.

Ok. My version in the case is ```Git version v0.3-alpha2-16-gc8f7357 (c8f735745b744fa26f345ca77bcc8b3d7bc60c55)```

**Comment by anmaped** [comment] 2018-11-29 17:57
So everything is right. You are with the last version.

Regarding the config/default, you have to use the flag `--config-file` and use the proper config file.

**Comment by HenriqueMisson** [comment] 2018-11-30 00:39
Ok, thank you very much for your help André.

Just one other question. I tried to install in other machine, and I got the error 
```
[ERROR] The compilation of rmtld3synth failed at "make all".

#=== ERROR while installing rmtld3synth.0.3-dev ===============================#
# opam-version 1.2.2
# os           linux
# command      make all
# path         /home/henrique/.opam/4.03.0/build/rmtld3synth.0.3-dev
# compiler     4.03.0
# exit-code    2
# env-file     /home/henrique/.opam/4.03.0/build/rmtld3synth.0.3-dev/rmtld3synth-3121-a71bb4.env
# stdout-file  /home/henrique/.opam/4.03.0/build/rmtld3synth.0.3-dev/rmtld3synth-3121-a71bb4.out
# stderr-file  /home/henrique/.opam/4.03.0/build/rmtld3synth.0.3-dev/rmtld3synth-3121-a71bb4.err
### stdout ###
# echo "let git = \"`git describe --tags` (`git rev-parse HEAD`)\n`uname -m -o` `date +\"%Y-%m-%d %H:%M\"`\"" > src/version.ml
# cp src/interface/z3solver_newAPI.ml src/interface/z3solver_.ml
# cp src/interface/mathkernel_call.ml src/interface/mathkernel_call_.ml
# echo "(* dummy js interface *)" >> src/js/helper_.ml
# dune build --profile release @install
# Makefile:12: recipe for target 'all' failed
### stderr ###
# File "src/interface/dune", line 5, characters 89-91:
# 5 |   (libraries       rmtld3synth.helper rmtld3synth.rmtld3.extension sexplib ppx_sexp_conv Z3)
#                                                                                              ^^
# Error: Library "Z3" not found.
# Hint: try: dune external-lib-deps --missing --profile release @install
# make: *** [all] Error 1



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install rmtld3synth 0.3-dev
No changes have been performed
```
I think is due to the case sensitive of ocamlfind, because I have z3 and not Z3
```
henrique@henrique-VirtualBox:~$ ocamlfind query z3
/home/henrique/.opam/4.03.0/lib/z3
henrique@henrique-VirtualBox:~$ ocamlfind query Z3
ocamlfind: Package `Z3' not found
```
Do you know what I can do to solve this?

**Comment by anmaped** [comment] 2018-11-30 14:05
How have you installed z3?

**Comment by anmaped** [comment] 2018-11-30 15:32
ok. Just replace Z3 to z3 in `src/interface/dune`.

**Comment by anmaped** [comment] 2018-11-30 15:33
Could you verify if the same happens with Z3 4.7.x ?

**Comment by HenriqueMisson** [comment] 2018-11-30 15:43
> ok. Just replace Z3 to z3 in `src/interface/dune`.

I had already done that, but I have re-installed rmtld3synth and the file was replaced. So, I did this again and then ```make all```.  From now I have the error:
 ```
File "src/interface/z3solver_.ml", line 21, chaaracters 5-23:
Error: Unbound module Rmtld3synth_helper
```
Do I need to change all "Z3" to "z3" in this file too?

**Comment by anmaped** [comment] 2018-11-30 15:56
First, test  Z3 4.7.x or compile Z3 manually. I have to know why Z3 change to z3, if it is a matter of the opam package or the z3 git version.

**Comment by HenriqueMisson** [comment] 2018-11-30 21:10
I tried to install Z3 4.7.1 by downloading the source code from ```https://github.com/z3prover/z3/releases``` and then the steps to compile it and install. I had the message ```Z3 was successfully installed.```, but when I tried to see the version, I had the message that "z3 is currently not installed".

So I tried to compile and install Z3 manually.

Now when I tried to install rmtld3synth I had other error in the compilation:
```
[ERROR] The compilation of rmtld3synth failed at "make all".

#=== ERROR while installing rmtld3synth.0.3-dev ===============================#
# opam-version 1.2.2
# os           linux
# command      make all
# path         /home/henrique/.opam/4.03.0/build/rmtld3synth.0.3-dev
# compiler     4.03.0
# exit-code    2
# env-file     /home/henrique/.opam/4.03.0/build/rmtld3synth.0.3-dev/rmtld3synth-7460-ad8886.env
# stdout-file  /home/henrique/.opam/4.03.0/build/rmtld3synth.0.3-dev/rmtld3synth-7460-ad8886.out
# stderr-file  /home/henrique/.opam/4.03.0/build/rmtld3synth.0.3-dev/rmtld3synth-7460-ad8886.err
### stdout ###
# echo "let git = \"`git describe --tags` (`git rev-parse HEAD`)\n`uname -m -o` `date +\"%Y-%m-%d %H:%M\"`\"" > src/version.ml
# cp src/interface/z3solver.ml src/interface/z3solver_.ml
# cp src/interface/mathkernel_call.ml src/interface/mathkernel_call_.ml
# echo "(* dummy js interface *)" >> src/js/helper_.ml
# dune build --profile release @install
# Makefile:12: recipe for target 'all' failed
### stderr ###
# File "dune-project", line 1, characters 11-14:
# 1 | (lang dune 1.5)
#                ^^^
# Error: Version 1.5 of dune is not supported.
# Supported versions:
# - 0.0
# - 1.0 to 1.2
# make: *** [all] Error 1



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install rmtld3synth 0.3-dev
No changes have been performed
```
However, if I see the dune version I have: "1.2.1".

**Comment by anmaped** [comment] 2018-11-30 22:01
The z3 package spelling problem is now managed automatically in 50f1432612b4c5e619deaf39204ce056ef675b6b.

**Comment by HenriqueMisson** [comment] 2018-11-30 23:06
> So it says `Error: Version 1.5 of dune is not supported.`. Why have you not installed dune 1.5 ? You need dune 1.5.

In fact, dune was installed automatically, and the message was 
```
Error: Version 1.5 of dune is not supported.
Supported versions:
- 0.0
- 1.0 to 1.2
```

**Comment by anmaped** [comment] 2018-11-30 23:08
@HenriqueMisson You are using dune 1.2 and you require dune 1.5.

**Comment by HenriqueMisson** [comment] 2018-11-30 23:31
Now I got it. 

Thank you again André.

**Comment by anmaped** [comment] 2018-11-30 23:33
rmtld3synth is now using dune since commit e75d324f40f0fbfdf1e60ba51b876430d4cbc12c.

**Comment by HenriqueMisson** [comment] 2018-12-02 00:44
Andre, to write monitors in this new version we need to include the flag --config/file as you said. But this file can be for exemple the default (config/default)? I tried many combinations, but I could not generate a monitor.

I mean, if we want to generate the exemple monitor ```rmtld3synth --synth-cpp11 --input-latexeq
"(a \rightarrow ((a \lor b) \until_{<10} c)) \land \int^{10} c < 4" --out-src="mon1"``` we need to add the flag --config/file?

**Closed** 2018-12-02 01:31 UTC
